### ISSUE TITLE
The ngx-onboarding doesn't properly work with some material components

### ISSUE THREAD

**Issue by fleuth96** [rosen-group/ngx-onboarding#17]
It doesn't work with the following material components:  Tabs, Sidenav.

All elements inside these componentes won't be properly highlighted. They get completely covered instead of just being highlighted.

The following image shows the issue.

![highlighting_issue](https://user-images.githubusercontent.com/26691274/48182828-00210e80-e32d-11e8-8d4b-76f7f9deb945.JPG)

**Comment by MichaelKirchner** [comment]
same like #14
