### ISSUE TITLE
The ngx-onboarding doesn't work properly in a popup window

### ISSUE THREAD

**Issue by afcaceres** [rosen-group/ngx-onboarding#38]
The problem is that in the popup window the controls selected to be explained are shown dark and not light like in the rest of the window.

![ngx-onboarding popup](https://user-images.githubusercontent.com/47751600/52963651-5fe87600-336e-11e9-9b65-896b3a40a81a.png)

**Comment by SDohle** [comment]
Hi,

I've just released version 1.2.2 which should fix the problem. Can you please test it, @afcaceres  
Thanks!

**Comment by SDohle** [comment]
@afcaceres Can you confirm the bug is fixed with version 1.2.2?

**Comment by afcaceres** [comment]
Hi, 

I have been testing the new release, but it doesn't work completely good.

Now the pop-up window is displayed, but it doesn't indicate the control I want to explain. It is not possible to explain a control that is inside of the popup window

Thanks!

**Comment by SDohle** [comment]
Thanks for Thema Feedback, @afcaceres

@MichaelKirchner

**Comment by MichaelKirchner** [comment]
Hi @afcaceres ,
can you add a screenshot?
Thanks!

**Comment by afcaceres** [comment]
Hi @MichaelKirchner 

In this picture it should be remark the cancel button

![image](https://user-images.githubusercontent.com/47751600/54031462-cfd36a80-417c-11e9-933f-6bd20a7dadd5.png)

Thanks

**Comment by miller45** [comment]
Test comment from me

**Comment by miller45** [comment]
@afcaceres can you add some details to the "popup" dialog? 
Can you provide and html snippet with the button? 
Is the popup maybe embedded in an iframe?

**Comment by afcaceres** [comment]
Hi @miller45 

We use Devexpress controls for the popup and the button

 <dx-popup
  class="popup"
  width="60%"
  [height]="popupHeight"
  [showTitle]="true"
  title="Upload Report"
  [dragEnabled]="false"
  [closeOnOutsideClick]="false"
  [showCloseButton]= "false"
  [visible]="isVisible"
  (onHidden)="onPopupHidden()"
  (onShown)="onPopupShown()">
  <div *dxTemplate="let data of 'content'">
    <div fxLayout="row" fxLayoutGap="3%" fxLayoutAlign="center">
 		<div  fxLayout="row" fxLayoutGap="3%" fxLayoutAlign="end" class="form-container__buttons">
			<dx-button 
				id="saveBtn"
				width="90" 
				text="Save"
				type="success"  
				[useSubmitBehavior]="true"
				validationGroup="customerData"
				(onClick)="onSaveData()">
			</dx-button>
			<dx-button width="90"
				id="cancelBtn" 
				text="Cancel"
				type="danger">
			</dx-button>
		</div>
	</div>
	</div>
</dx-popup>

**Comment by SDohle** [comment]
@MichaelKirchner

**Comment by miller45** [comment]
After installing devExtreme controls in our demo and you snippet app I could reproduce the problem...
The shadow of our onboarding was behind the shadow of the dxPopup...at least in my example I have fix for the problem.

**Comment by SDohle** [comment]
Hi @afcaceres,
i've released version 1.2.4 with the bugfix just now. Can you test it please. Thanks!

Best regards 
Steffen

**Comment by miller45** [comment]
@afcaceres Does it work now?

**Comment by afcaceres** [comment]
Hi @SDohle @miller45 

It works perfect!

Thank you very much!

Angelica

**Comment by SDohle** [comment]
Hi Angelica,
Thanks for testing & feedback! 👍
