### ISSUE TITLE
onboarding.service.spec.ts has lint issues

### ISSUE THREAD

**Issue by miller45** [rosen-group/ngx-onboarding#45]
Just ran the the npm lint job and this is what showed up:
```
ERROR: ngx-onboarding/projects/ngx-onboarding/src/lib/services/onboarding.service.spec.ts[32, 44]: variable 'getOnboardingItems' used before declaration
ERROR: ngx-onboarding/projects/ngx-onboarding/src/lib/services/onboarding.service.spec.ts[47, 28]: variable 'getHtmlElements' used before declaration
ERROR: ngx-onboarding/projects/ngx-onboarding/src/lib/services/onboarding.service.spec.ts[50, 46]: variable 'getOnboardingItems' used before declaration
ERROR: ngx-onboarding/projects/ngx-onboarding/src/lib/services/onboarding.service.spec.ts[64, 55]: variable 'getOnboardingItems' used before declaration
ERROR: ngx-onboarding/projects/ngx-onboarding/src/lib/services/onboarding.service.spec.ts[130, 40]: variable 'getOnboardingItems' used before declaration
```
We should adjust the tslint rules or push the constant to the top of the spec file...
Anyway, @SDohle why is our pull request build not running the lint job?

**Comment by SDohle** [comment]
I will check this

**Comment by SDohle** [comment]
With PR #46 lint will be part of the build and the output will be:

> ngx-onboarding-app@1.2.3 lint /home/vsts/work/1/s
> ng lint
> 
> Linting "ngx-onboarding-app"...
> 
> All files pass linting.
> Linting "ngx-onboarding-app-e2e"...
> 
> All files pass linting.
> Linting "ngx-onboarding"...
> 
> All files pass linting.
