### ISSUE TITLE
Angular 9 (ivy) compatibility

### ISSUE THREAD

**Issue by coonmoo** [rosen-group/ngx-onboarding#54]
We just updated to Angular 9 RC and get the following error when compiling our solution (works fine on Angular8):

```
chunk {mainERROR in Failed to compile entry-point @rosen-group/ngx-onboarding due to compilation errors:
} main.js, main.js.map (main) 2.06 kB [initial]node_modules/@rosen-group/ngx-onboarding/fesm5/rosen-group-ngx-onboarding.js(2047,30): error TS-991010: Value at position 1 in the NgModule.imports of OnboardingModule is not a reference: [object Object]
 [rendered]


```

Are there any plans to update to Angular 9? Would be very happy :)

**Comment by SDohle** [comment]
Hi @coonmoo,
of course we have plans to update to Angular 9 compatibility.
But there is not any schedule yet. It will probably take place short after the final Angular 9 release.

Best regards
Steffen

**Comment by SDohle** [comment]
Just to clarify that we are talking about the same issue @coonmoo -
the error only occurs with ivy? if you use Angular with and disable Ivy everything is fine?

**Comment by SDohle** [comment]
#58

**Comment by SDohle** [comment]
https://www.npmjs.com/package/@rosen-group/ngx-onboarding/v/1.4.0
