### ISSUE TITLE
ERROR in The target entry-point "@rosen-group/ngx-onboarding" has missing dependencies:  - lodash-es

### ISSUE THREAD

**Issue by itsmedeepakupadhya** [rosen-group/ngx-onboarding#83]
in Angular 9 : ERROR in The target entry-point "@rosen-group/ngx-onboarding" has missing dependencies:
 - lodash-es
![Capture](https://user-images.githubusercontent.com/47023490/126534056-af5970c0-712a-44dc-833a-46e2a39fce7f.JPG)

i am using     "@rosen-group/ngx-onboarding": "^1.7.0", in package.json and using import statements like this 
import {OnboardingItem, OnboardingService} from '@rosen-group/ngx-onboarding';

so what i am missing  ?

**Comment by SDohle** [comment]
Hi,

the module has lodash-es as a peer dependency. Please just install the package and add it tou your package.json for your application:

`npm i --save "lodash-es`

Is your problem solved by this?

Best regards
Steffen

**Comment by SDohle** [comment]
The readme is updated. Please contact me if you have any further questions.
Best regards

**Comment by itsmedeepakupadhya** [comment]
Yes. Thanks
