### ISSUE TITLE
Consider removing lodash-es usage

### ISSUE THREAD

**Issue by solkaz** [rosen-group/ngx-onboarding#88]
I wanted to ask if there was a specific reason to use `lodash-es` in the project? It uses the following utilities ([search result](https://github.com/rosen-group/ngx-onboarding/search?l=TypeScript&q=lodash-es)), which either have native equivalents, or easy replacements:

- [each (actually forEach)](https://youmightnotneed.com/lodash/#forEach) - Array#forEach can be used
- [filter](https://youmightnotneed.com/lodash/#filter) - Array#filter can be used
- [find](https://youmightnotneed.com/lodash/#find) - Array#find can be used
- [some](https://youmightnotneed.com/lodash/#some) - Array#some can be used
- isEmpty - no native method, but where being used, simple falsy checks might be good enough
  - [Usage 1](https://github.com/rosen-group/ngx-onboarding/blob/ddc9056fde5520ff8c74e1c8e9cff6145b3c6abb/projects/ngx-onboarding/src/lib/onboarding-item.component.ts#L120) - seems to be checking if a string is empty
  - [Usage 2](https://github.com/rosen-group/ngx-onboarding/blob/ddc9056fde5520ff8c74e1c8e9cff6145b3c6abb/projects/ngx-onboarding/src/lib/services/local-storage-seen-selectors.service.ts#L31) - checking result of [`Storage.getItem`](https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem), which will either be a string or null

**Comment by SDohle** [comment]
Hi,
we created this module to consume it in a project which is using lodash. There is no other technical reason.
Feel free to provide a pull request because I'm not sure if some of our developers will find time for that refactoring.
